### ISSUE TITLE
Add eslint to the project

### ISSUE THREAD

**Issue by trmazurkevych** [volodymyr9122/BotKitLearning#1]
it keeps the code style consistent and prevents bugs.

Using default Airbnb config is enough https://eslint.org/docs/user-guide/getting-started

**Comment by volodymyr9122** [comment]
saved as dev dependency, inited, but can't run via npm 
![eslint_not_running](https://user-images.githubusercontent.com/15000632/46920926-b0854680-cffd-11e8-9aad-2b945c2aaa8f.png)

**Comment by trmazurkevych** [comment]
@volodymyr9122 please tag me. I won't see the message otherwise
Can't help with this problem. Try to reinstall. If it won't work google it!

**Comment by volodymyr9122** [comment]
added
